version: '3.8'

services:
  vue-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: vue-app-dev
    ports:
      - "3000:3000"  # Vite dev server port
      - "80:80"      # Nginx port (optional)
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    volumes:
      # Mount source code để hot reload
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./package.json:/app/package.json
      - ./vite.config.js:/app/vite.config.js
      # Mount node_modules để cache dependencies
      - node_modules:/app/node_modules
      # Mount logs
      - ./logs/nginx:/var/log/nginx
    networks:
      - vue-network
    command: npm run dev

networks:
  vue-network:
    driver: bridge

volumes:
  node_modules:
    driver: local
