version: '3.8'

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-app-nginx
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      # Mount nginx logs để dễ debug
      - ./logs/nginx:/var/log/nginx
    networks:
      - vue-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  vue-network:
    driver: bridge

# Optional: Nếu muốn sử dụng external volume cho logs
volumes:
  nginx-logs:
    driver: local
